---
- name: Install chocolatey 
  hosts: win
  tasks:
    - name: Install chocolatey
      win_chocolatey:
          name:
           - chocolatey
           - chocolatey-core.extension
          state: present
